remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
gem "github-pages", group: :jekyll_plugins
title: [Maya Venkatraman]
description: [An intro to me and my work :)]
logo: IMG_4834.jpg

social_links:
  - name: "GitHub"
    url: https://github.com/mv2731
  - name: "LinkedIn"
    url: https://www.linkedin.com/in/maya-venkatraman-2b2398156
  - name: "Scholar"
    url: https://scholar.google.com/citations?user=NaZR814AAAAJ&hl=en
