import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Navigation at the very top */}
        <nav className="w-full bg-white/80 backdrop-blur-sm border-b border-orange-200 z-50">
          <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="flex justify-between h-16 items-center">
              <div className="flex-shrink-0 font-bold text-xl text-orange-900">Maya Venkatraman</div>
              <div className="hidden sm:flex space-x-8">
                <a href="/" className="text-orange-900 hover:text-orange-500">Home</a>
                <a href="/reads" className="text-orange-900 hover:text-orange-500">Reads</a>
                <a href="/publications" className="text-orange-900 hover:text-orange-500">Publications</a>
              </div>
            </div>
          </div>
        </nav>
        {/* Large Orange Tree Banner */}
        <div style={{ width: '100%', position: 'relative', height: '250px', marginBottom: '0', overflow: 'hidden' }}>
          <img
            src="/orange-tree.jpg"
            alt="Orange tree against blue sky"
            style={{ width: '100%', height: '100%', objectFit: 'cover', objectPosition: 'center' }}
          />
        </div>
        {children}
      </body>
    </html>
  );
}
